# DATABASE_URL=postgres://user:password@psql:5432/database
services:
  your-app: # change this to fit your app's name
    restart: always # kill it and let it start again to test db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on: 
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    healthcheck:
      test: "pg_isready -U user -d database"
      interval: 5s
      retries: 3
