FROM node:alpine
WORKDIR /usr/docker/uplace/
COPY package.json package-lock.json .
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build
EXPOSE 3000
# CMD npx prisma db push && npm run serve
CMD sleep 100000
