# DATABASE_URL=postgres://postgres:password@psql:5432/database
services:
  your-app: # change this to fit your app's name
    restart: always # kill it and let it start again to test db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on: 
      - psql
  psql:
    build:
      context: ./postgresql
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
